/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ArticleArticleImage model module.
 * @module model/ArticleArticleImage
 * @version 1.0.0
 */
class ArticleArticleImage {
    /**
     * Constructs a new <code>ArticleArticleImage</code>.
     * @alias module:model/ArticleArticleImage
     */
    constructor() { 
        
        ArticleArticleImage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ArticleArticleImage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArticleArticleImage} obj Optional instance to populate.
     * @return {module:model/ArticleArticleImage} The populated <code>ArticleArticleImage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArticleArticleImage();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} data
 */
ArticleArticleImage.prototype['data'] = undefined;

/**
 * @member {String} name
 */
ArticleArticleImage.prototype['name'] = undefined;






export default ArticleArticleImage;

