/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArticleArticleImage from './ArticleArticleImage';

/**
 * The Article model module.
 * @module model/Article
 * @version 1.0.0
 */
class Article {
    /**
     * Constructs a new <code>Article</code>.
     * @alias module:model/Article
     * @param articleImage {module:model/ArticleArticleImage} 
     * @param articleTitle {String} 
     * @param articleDate {Date} 
     * @param articlePost {String} 
     */
    constructor(articleImage, articleTitle, articleDate, articlePost) { 
        
        Article.initialize(this, articleImage, articleTitle, articleDate, articlePost);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, articleImage, articleTitle, articleDate, articlePost) { 
        obj['articleImage'] = articleImage;
        obj['articleTitle'] = articleTitle;
        obj['articleDate'] = articleDate;
        obj['articlePost'] = articlePost;
    }

    /**
     * Constructs a <code>Article</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Article} obj Optional instance to populate.
     * @return {module:model/Article} The populated <code>Article</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Article();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('articleImage')) {
                obj['articleImage'] = ArticleArticleImage.constructFromObject(data['articleImage']);
            }
            if (data.hasOwnProperty('articleTitle')) {
                obj['articleTitle'] = ApiClient.convertToType(data['articleTitle'], 'String');
            }
            if (data.hasOwnProperty('articleDate')) {
                obj['articleDate'] = ApiClient.convertToType(data['articleDate'], 'Date');
            }
            if (data.hasOwnProperty('articlePost')) {
                obj['articlePost'] = ApiClient.convertToType(data['articlePost'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Article.prototype['_id'] = undefined;

/**
 * @member {module:model/ArticleArticleImage} articleImage
 */
Article.prototype['articleImage'] = undefined;

/**
 * @member {String} articleTitle
 */
Article.prototype['articleTitle'] = undefined;

/**
 * @member {Date} articleDate
 */
Article.prototype['articleDate'] = undefined;

/**
 * @member {String} articlePost
 */
Article.prototype['articlePost'] = undefined;






export default Article;

